import type { Metadata } from "next";
import "./globals.scss";
import  ReduxProvider  from '../components/ReduxProvider'


export const metadata: Metadata = {
  title: "This is Japan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>{children}</body>
      </ReduxProvider>
    </html>
  );
}
